name: '合并-FFF到目录'

on:
  schedule:
    - cron: '45 01,05,09,12,16 * * *'  # UTC
  workflow_dispatch:
    inputs:
      environment:
        description: 'hebing-FFF'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Install cryptography
      run: |
        python -m pip install cryptography       
        
    - name: Run Python script
      run: python 合并FFF.py


      
    - name: Commit changes
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add reaslt-CAIJI-out-all/hebing-FFF.txt
          git commit -m ":tv:  (special)AutoUpdate $(date -d "+8 hours" +'%Y%m%d')"
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
