name: 组播扫描Multi+Fofa

on:
  schedule:
  
    - cron: "*/3 * * * *"    #每3分钟执行一次
#    - cron: "25 23,3,7,11,15 * * *"  #定时执行暂时不使用
  workflow_dispatch:
    分支:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
      
    - name: Run Multitest Script
      #working-directory: iptv/speedtest
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./multi_test.sh
        bash ./fofa.sh
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "actions@github.com"  #设置当前仓库的Git用户邮箱为actions@github.com
        git config --local user.name "GitHub Action"  #设置当前仓库的Git用户名为GitHub Action
        git add .    #将当前目录下的所有更改添加到暂存区
        git commit -am "Automatic update"  #将暂存区的更改提交，-a表示自动将所有已跟踪文件的更改和删除添加到提交中，-m后面跟的是提交信息
	git checkout main    #切换到本地main分支
	git push origin main  #origin是远程仓库的默认名称，main是你想要推送到的分支名称
